
import StyledComponentsRegistry from "@/app/lib/registry";
import {GlobalStyles} from "@/app/styles/globalStyles";

export const metadata = {
    title: 'Create Next App', description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (<html lang="en">
    <body>
    <GlobalStyles />
    <StyledComponentsRegistry>
        {children}
    </StyledComponentsRegistry>
    </body>
    </html>)
}
